### PR TITLE
Crm/brca

### PR DESCRIPTION
**Pull request by niamhat**
models.py - Added 500x coverage to models
Panels - Added CRM panels and the bed file to go with them
import.py - Added 500x coverage and gaps, CRM/BRCA assay choices, added if statement for genescreen and hotspot choices as no genescreen option for CRM/BRCA
analysis-depth.html  & download-report.html - Added coverage for 500x
test_data - Added CRM and BRCA test data 
utils.py - Now covers gaps at 500

### CODE REVIEW

**Review by erikwaskiewicz — COMMENTED** [review]
Happy with changes, on the whole looks really good. I've made some edits, can you review them and then we can merge when we're both happy?
- Resynced with development branch so it needed some merge conflicts fixing
- Some 500x sections were missing from the report summary tab and the PDF download (one was just typo as 5000x in a loop rather than 500)
- Also added 500x section to the LIMS XML
- Added `GeneRead` to the assay names
- Made the artefact lists from TSO500 work with CRM too
- Updated panels fixtures to match live database (yours had the whole database in there, not just panels, see command on readme for how to do just a specific model)

Can you also add some more CRM test data? There were three samples in the sample list but I had to delete 2 as there was only coverage for one of them. If possible one sample per panel would be good

**Comment by erikwaskiewicz** [comment]
There's a lot of commits from different branches that have all appeared in here - use this link to just see the changes that need reviewing - https://github.com/AWGL/somatic_db/compare/e6cbd52..66df04a

**Comment by erikwaskiewicz** [comment]
Also, a couple of pipeline things, but this is more of a note for me when it comes to the pipeline code review:
- Loads of variants because its showing every transcript for each variant, we'll need to look at how it applies the preferred transcripts
- Can we add the Gnomad pop max so its pulled into SVD
- Can we add run ID to the samples_*.csv file for the database upload, so it doesnt have to be typed into the command line

**Comment by niamhat** [comment]
Changes agreed. Added crm test data for more panels

**Comment by erikwaskiewicz** [comment]
Happy with changes, I've filtered the variant list to exclude all the XM transcripts so the test data is a bit cleaner. All looks good to merge :)

**Pull request merged**
