### PR TITLE
Issue69

### LINKED ISSUE #69: Artefact Display
- Display common artefacts alongside polys at the bottom. 
- Will need to be assay and genome build specific.
- Possible add in VAF cut off to allow for the ASXL1 low VAF variants to automatically be classified as an artefact.

### PR DESCRIPTION
**Pull request by SophieS9**
Close #69 

Addition of artefact list to go alongside poly list. Linked to assay and genome build. Artefacts then display at the bottom of the page above polys. Artefacts are added in the same way that polys are, via the options page with the need for a check from a second person. Needs variant list "TSO500_DNA_b38_artefacts" added to the backend and needs update to models to add assay to variantovariantlist. 

Unit tests all pass. 

Edit - added query to get all igv variant checks which are not geniune or pending between a date range. Idea is to pipe into sort and uniq to count the instance of each as follows:
```
python manage.py shell < /home/ew/somatic_db/queries/pull_igv_checks.py | sort | uniq -c
```

### CODE REVIEW

**Comment by erikwaskiewicz** [comment]
Happy with code you've done but I've made some edits, can you review please:
- Added ability to add specific VAF cutoff for artefact lists (can you test with variants above and below the cutoff? if variant exactly matches the VAF cutoff then it should be kept)
- Made into one single list on analysis page with flags for poly/artefact (rather than two seperate sections)
- Moved assay from VariantToVariantList model to VariantList
- Simplified the applying of variant lists section in the utils

**Comment by erikwaskiewicz** [comment]
Also just added a loop to make the links from the options page, rather than copy and pasting a chunk each time

**Comment by erikwaskiewicz** [comment]
Fixed some bugs:
- Large variants should wrap better now, can you test with the one you had? I just wrote some really long nonsense in for testing
- VAF cutoff should now be saved when adding new artefact
- On the section at the bottom of the SNVs page, add to the 'artefact' badge when its got a VAF cutoff
- Also changed the Gnomad to say 'Not found' imstead of -1.00000 when its not in gnomad

**Comment by SophieS9** [comment]
- Added sorting artefact page
- If a variant is an artefact with a VAF cut off, it automatically pre-populates the igv check with artefact if it's above the cut off. I think that's OK, but we'll probably have to explain it (I set this one as artefact <10%):
image

**Comment by SophieS9** [comment]
All good. Unit tests all working. Merge to development.

**Pull request closed without merging**
